### PR TITLE
Feat/contact

### PR DESCRIPTION
**Pull request by hanasay**
Add in new feature, Contact Page.

### CODE REVIEW

**Comment by hanasay** [comment]
There's another thing needs to remind, you have to set your email account & passwd into /.env

It should look like this
```
EMAIL_USER=email@address
EMAIL_PASS=application_passwd
```

**Comment by AU2A** [comment]
Some development suggestions, though they don't significantly impact us:

1. Since the mail server is not part of the Vue project, it’s not suitable to place it within the `src` directory. It’s recommended to create a separate folder in the root directory.
Ex.
```
folder/
┣━ public/
┣━ mail/
┣━ src/
┣━ ...
```

2. Continuing from the above, because the mail server is an independent system, it would be better to create a dedicated project for it. The libraries it uses should also be separated; keeping them under the Vue project will unnecessarily increase project's size.

3. You can create an example environment file using the `.env.example`, and in the documentation, instruct users to copy and rename it for their use.

**Review by AU2A — APPROVED** [review]
Some development suggestions, though they don't significantly impact us:

1. Since the mail server is not part of the Vue project, it’s not suitable to place it within the `src` directory. It’s recommended to create a separate folder in the root directory.
Ex.
```
folder/
┣━ public/
┣━ mail/
┣━ src/
┣━ ...
```

2. Continuing from the above, because the mail server is an independent system, it would be better to create a dedicated project for it. The libraries it uses should also be separated; keeping them under the Vue project will unnecessarily increase project's size.

3. You can create an example environment file using the `.env.example`, and in the documentation, instruct users to copy and rename it for their use.

**Comment by hanasay** [comment]
> Some development suggestions, though they don't significantly impact us:
> 
> 1. Since the mail server is not part of the Vue project, it’s not suitable to place it within the `src` directory. It’s recommended to create a separate folder in the root directory.
>    Ex.
> 
> ```
> folder/
> ┣━ public/
> ┣━ mail/
> ┣━ src/
> ┣━ ...
> ```
> 
> 2. Continuing from the above, because the mail server is an independent system, it would be better to create a dedicated project for it. The libraries it uses should also be separated; keeping them under the Vue project will unnecessarily increase project's size.
> 3. You can create an example environment file using the `.env.example`, and in the documentation, instruct users to copy and rename it for their use.

I'll do refactor in future

**Comment by hanasay** [comment]
due to we only have one project, let me put back-end code in front-end for temporary.

uwu

**Pull request merged**
